- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

# changed this as part of latest python3-devel from repos have upgraded openssl-libs but other openssl packages are old in AMI, so mismatch occured. we are upgrading before installing python or after
- name: upgrade openssl packages safely
  ansible.builtin.dnf:
    name:
      - openssl
      - openssl-libs
    state: latest


- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml